### ISSUE TITLE
Build dependency dike missing

### ISSUE THREAD

**Issue by davidpsys** [TheThingsNetwork/server-devenv#3]
Could you please add a repository for the application dike which is linked in the docker-compose.xml, having a hard time finding it online.

**Comment by devlaam** [comment]
Hmm, this repro is there, @johanstokking: make it public?

**Comment by johanstokking** [comment]
Yes, was not GitHub-ready yet, now it is and it's public! I'll update the READMEs also to get the right env vars

**Comment by devlaam** [comment]
Super @johanstokking !
