### ISSUE TITLE
unable to create/open lock file:/data/db/mongod.lock

### ISSUE THREAD

**Issue by openiod** [TheThingsNetwork/server-devenv#6]
Mac OS X: error mongod while executing ./buildup.sh

Attaching to serverdevenv_mongodb_1, serverdevenv_influxdb_1, serverdevenv_rabbitmq_1, serverdevenv_jolie_1, serverdevenv_croft_1
mongodb_1  | 2015-11-12T20:54:05.403+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to create/open lock file: /data/db/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating
mongodb_1  | 2015-11-12T20:54:05.404+0000 I CONTROL  [initandlisten] dbexit:  rc: 100

**Comment by hans-d** [comment]
Souns like you map a local folder to the data volume for mongodb. In combination with virtualbox this results in these kind of error messages

**Comment by openiod** [comment]
Newbe docker here. I do launchpad: Docker Quickstart Terminal. Then ./buildup.sh
Where to put /data/db ?

**Comment by hans-d** [comment]
Update docker-compose.yml

From
 ```
 volumes:
    - /var/lib/docker/mongo/mongodb:/data/db
```

To
```
 volumes:
    - /data/db
```

This will store the data inside the volume, not mapped to a local folder.

**Comment by openiod** [comment]
removed the local path and see error below. Same error after removing all local paths in docker-compose.yml and staging.yml

Step 9 : RUN go build .
 ---> Running in 42cc6e648e17
# github.com/thethingsnetwork/croft
./server.go:88: cannot use &stat.Rxnb (type *uint) as type *int in field value
./server.go:89: cannot use &stat.Rxok (type *uint) as type *int in field value
./server.go:90: cannot use &stat.Rxfw (type *uint) as type *int in field value
./server.go:92: cannot use &stat.Dwnb (type *uint) as type *int in field value
./server.go:93: cannot use &stat.Txnb (type *uint) as type *int in field value
ERROR: Service 'croft' failed to build: The command '/bin/sh -c go build .' returned a non-zero code: 2

**Comment by johanstokking** [comment]
That's a build error, please build with --no-cache and/or pull with docker-compose pull. This has been fixed and is not related to docker

**Comment by openiod** [comment]
Ok. in ./buildup.sh changed first line to: docker-compose build --no-cache
-> error is gone.

than cleaned up folder (rm -rf) and started all over again:

git clone https://github.com/TheThingsNetwork/server-devenv.git
git clone https://github.com/TheThingsNetwork/croft.git
git clone https://github.com/TheThingsNetwork/jolie.git
cd server-devenv
docker-compose pull
first line buildup.sh -> docker-compose build --no-cache
./buildup.sh

still mongodb error:

Attaching to serverdevenv_mongodb_1, serverdevenv_influxdb_1, serverdevenv_rabbitmq_1, serverdevenv_jolie_1, serverdevenv_croft_1
mongodb_1  | 2015-11-12T21:57:20.216+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to create/open lock file: /data/db/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating
influxdb_1 | influxdb configuration:
mongodb_1  | 2015-11-12T21:57:20.216+0000 I CONTROL  [initandlisten] dbexit:  rc: 100
influxdb_1 | ### Welcome to the InfluxDB configuration file.

**Comment by openiod** [comment]
removed virtual machine in VirtualBox Manager and created again by restart Launchpad Docker Quickstart Terminal. 
docker-compose pull
./buildup.sh

Now NO errors for mongodb :-) :-)
